public class Setdemo {
    public void Setmethod(){
        List<String> StrList = new List<String>{'A','B'};
        Set<string> StrSet = new Set<string>();
        Set<string> StrSet2 = new Set<string>();
        Boolean b;
        
        StrSet.add('A');
        StrSet.add('B');
        StrSet.add('C');
        StrSet.add('D');
        
        system.debug('StrSet Sixe = ' + StrSet.Size() );
        
    } 
}